import { AuditEvent, DemoUser, Goal } from "@/lib/types";

export const DEMO_USERS: DemoUser[] = [
  {
    id: "u1",
    name: "Avery Johnson",
    email: "avery.johnson@alignx.com",
    role: "employee",
    department: "Engineering",
    title: "Senior Software Engineer",
  },
  {
    id: "u2",
    name: "Morgan Chen",
    email: "morgan.chen@alignx.com",
    role: "employee",
    department: "Engineering",
    title: "Platform Engineer",
  },
  {
    id: "u3",
    name: "Riley Brooks",
    email: "riley.brooks@alignx.com",
    role: "employee",
    department: "Sales",
    title: "Account Executive",
  },
  {
    id: "u4",
    name: "Sam Patel",
    email: "sam.patel@alignx.com",
    role: "employee",
    department: "Marketing",
    title: "Growth Marketing Lead",
  },
  {
    id: "u5",
    name: "Casey Wu",
    email: "casey.wu@alignx.com",
    role: "employee",
    department: "HR",
    title: "People Operations Specialist",
  },
  {
    id: "u6",
    name: "Jordan Lee",
    email: "jordan.lee@alignx.com",
    role: "manager",
    department: "Sales",
    title: "Regional Sales Manager",
  },
  {
    id: "u7",
    name: "Taylor Reed",
    email: "taylor.reed@alignx.com",
    role: "manager",
    department: "Engineering",
    title: "Engineering Manager",
  },
  {
    id: "u8",
    name: "Alex Rivera",
    email: "alex.rivera@alignx.com",
    role: "admin",
    department: "Operations",
    title: "HRIS Administrator",
  },
];

export const DEMO_GOALS: Goal[] = [
  {
    id: "g1",
    employee: "Avery Johnson",
    title: "Improve platform reliability",
    description: "Reduce P1 incidents by 30% and automate SLA reporting by end of Q1.",
    quarter: "Q1",
    weightage: 40,
    progress: 62,
    shared: true,
    status: "approved",
    checkInNotes: "SRE runbooks updated; two incidents closed this month.",
    locked: true,
    department: "Engineering",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [
      {
        id: "c1",
        author: "Taylor Reed",
        text: "Strong measurable targets. Approved for Q1 tracking.",
        createdAt: "2026-01-15T10:00:00Z",
      },
    ],
    approvalNote: "Aligned with platform OKRs.",
  },
  {
    id: "g2",
    employee: "Avery Johnson",
    title: "Accelerate feature delivery",
    description: "Ship two client-requested modules with 95% test coverage by Q2.",
    quarter: "Q2",
    weightage: 35,
    progress: 28,
    shared: false,
    status: "submitted",
    checkInNotes: "Design review scheduled for module B.",
    locked: true,
    department: "Engineering",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g3",
    employee: "Avery Johnson",
    title: "Mentor junior engineers",
    description: "Conduct bi-weekly coaching sessions and complete 4 architecture walkthroughs in Q1.",
    quarter: "Q1",
    weightage: 25,
    progress: 45,
    shared: true,
    status: "approved",
    checkInNotes: "Two walkthroughs completed.",
    locked: true,
    department: "Engineering",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [],
    approvalNote: "Supports team development goals.",
  },
  {
    id: "g4",
    employee: "Morgan Chen",
    title: "Reduce API latency",
    description: "Decrease p95 API latency from 420ms to under 250ms by Q1 through caching and query optimization.",
    quarter: "Q1",
    weightage: 50,
    progress: 71,
    shared: true,
    status: "approved",
    checkInNotes: "Cache layer deployed to staging.",
    locked: true,
    department: "Engineering",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [],
    approvalNote: "Critical for customer SLA.",
  },
  {
    id: "g5",
    employee: "Morgan Chen",
    title: "Kubernetes cost optimization",
    description: "Lower non-prod cluster spend by 18% in Q2 without impacting release velocity.",
    quarter: "Q2",
    weightage: 50,
    progress: 15,
    shared: false,
    status: "draft",
    checkInNotes: "FinOps analysis in progress.",
    locked: false,
    department: "Engineering",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g6",
    employee: "Riley Brooks",
    title: "Increase enterprise pipeline",
    description: "Add $2.4M qualified pipeline in Q1 through outbound and partner referrals.",
    quarter: "Q1",
    weightage: 55,
    progress: 48,
    shared: false,
    status: "submitted",
    checkInNotes: "$1.1M qualified to date; two enterprise demos booked.",
    locked: true,
    department: "Sales",
    riskLevel: "high",
    dueDate: "2026-02-28",
    managerComments: [
      {
        id: "c2",
        author: "Jordan Lee",
        text: "Pipeline velocity is behind plan—focus on top 10 accounts.",
        createdAt: "2026-02-10T14:30:00Z",
      },
    ],
  },
  {
    id: "g7",
    employee: "Riley Brooks",
    title: "Improve win rate",
    description: "Raise closed-won rate from 22% to 30% in Q2 via improved discovery templates.",
    quarter: "Q2",
    weightage: 45,
    progress: 10,
    shared: true,
    status: "draft",
    checkInNotes: "New discovery deck drafted.",
    locked: false,
    department: "Sales",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g8",
    employee: "Riley Brooks",
    title: "Launch partner co-sell program",
    description: "Sign 3 strategic partners and generate 5 co-sell opportunities in Q3.",
    quarter: "Q3",
    weightage: 30,
    progress: 0,
    shared: true,
    status: "rejected",
    checkInNotes: "Needs clearer success metrics.",
    locked: false,
    department: "Sales",
    riskLevel: "high",
    dueDate: "2026-09-30",
    managerComments: [],
    approvalNote: "Rejected: revise with measurable partner KPIs.",
  },
  {
    id: "g9",
    employee: "Sam Patel",
    title: "Grow inbound MQL volume",
    description: "Increase marketing-qualified leads by 25% in Q1 through SEO and webinar campaigns.",
    quarter: "Q1",
    weightage: 40,
    progress: 58,
    shared: true,
    status: "approved",
    checkInNotes: "January webinar exceeded registration target by 12%.",
    locked: true,
    department: "Marketing",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [],
    approvalNote: "Approved.",
  },
  {
    id: "g10",
    employee: "Sam Patel",
    title: "Improve campaign ROI",
    description: "Achieve 3.5x blended ROAS on paid channels in Q2 while maintaining CAC under $180.",
    quarter: "Q2",
    weightage: 35,
    progress: 22,
    shared: false,
    status: "submitted",
    checkInNotes: "LinkedIn tests showing positive early signals.",
    locked: true,
    department: "Marketing",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g11",
    employee: "Sam Patel",
    title: "Refresh brand messaging",
    description: "Deliver updated messaging framework and 6 sales enablement assets by Q1.",
    quarter: "Q1",
    weightage: 25,
    progress: 80,
    shared: true,
    status: "approved",
    checkInNotes: "Four assets published; two in legal review.",
    locked: true,
    department: "Marketing",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [],
  },
  {
    id: "g12",
    employee: "Casey Wu",
    title: "Reduce time-to-hire",
    description: "Lower average time-to-hire from 52 to 40 days for engineering roles in Q1.",
    quarter: "Q1",
    weightage: 50,
    progress: 35,
    shared: false,
    status: "submitted",
    checkInNotes: "New interview loop pilot started.",
    locked: true,
    department: "HR",
    riskLevel: "high",
    dueDate: "2026-02-15",
    managerComments: [],
  },
  {
    id: "g13",
    employee: "Casey Wu",
    title: "Increase employee engagement",
    description: "Raise eNPS from 34 to 42 by Q2 through manager training and pulse action plans.",
    quarter: "Q2",
    weightage: 50,
    progress: 18,
    shared: true,
    status: "draft",
    checkInNotes: "Q1 pulse survey scheduled.",
    locked: false,
    department: "HR",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g14",
    employee: "Jordan Lee",
    title: "Hit regional revenue target",
    description: "Achieve $4.8M regional bookings in Q1 with 90% forecast accuracy.",
    quarter: "Q1",
    weightage: 60,
    progress: 52,
    shared: false,
    status: "approved",
    checkInNotes: "February pacing at 94% of plan.",
    locked: true,
    department: "Sales",
    riskLevel: "medium",
    dueDate: "2026-03-31",
    managerComments: [],
    approvalNote: "Regional OKR aligned.",
  },
  {
    id: "g15",
    employee: "Jordan Lee",
    title: "Develop sales managers",
    description: "Complete coaching plans for 5 AEs and improve team quota attainment to 85% in Q2.",
    quarter: "Q2",
    weightage: 40,
    progress: 20,
    shared: true,
    status: "approved",
    checkInNotes: "Coaching cadence established.",
    locked: true,
    department: "Sales",
    riskLevel: "low",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g16",
    employee: "Taylor Reed",
    title: "Improve sprint predictability",
    description: "Reach 85% sprint commitment reliability across 3 engineering squads in Q1.",
    quarter: "Q1",
    weightage: 50,
    progress: 67,
    shared: true,
    status: "approved",
    checkInNotes: "Squad B hit 88% reliability last sprint.",
    locked: true,
    department: "Engineering",
    riskLevel: "low",
    dueDate: "2026-03-31",
    managerComments: [],
  },
  {
    id: "g17",
    employee: "Taylor Reed",
    title: "Reduce production defects",
    description: "Cut escaped defects per release by 25% in Q2 through improved QA gates.",
    quarter: "Q2",
    weightage: 50,
    progress: 12,
    shared: false,
    status: "submitted",
    checkInNotes: "QA gate checklist drafted.",
    locked: true,
    department: "Engineering",
    riskLevel: "medium",
    dueDate: "2026-06-30",
    managerComments: [],
  },
  {
    id: "g18",
    employee: "Morgan Chen",
    title: "Security compliance uplift",
    description: "Close 100% of critical SOC 2 findings and pass internal audit by Q3.",
    quarter: "Q3",
    weightage: 40,
    progress: 5,
    shared: true,
    status: "submitted",
    checkInNotes: "8 of 12 findings remediated.",
    locked: true,
    department: "Engineering",
    riskLevel: "high",
    dueDate: "2026-09-30",
    managerComments: [
      {
        id: "c3",
        author: "Taylor Reed",
        text: "Prioritize remaining critical items before mid-Q2 review.",
        createdAt: "2026-02-18T09:15:00Z",
      },
    ],
  },
];

export const DEMO_AUDIT: AuditEvent[] = [
  {
    id: "a1",
    type: "goal_created",
    goalId: "g6",
    goalTitle: "Increase enterprise pipeline",
    actor: "Riley Brooks",
    role: "employee",
    timestamp: "2026-01-08T09:00:00Z",
    details: "Created sales goal for Q1 pipeline growth.",
  },
  {
    id: "a2",
    type: "approval",
    goalId: "g1",
    goalTitle: "Improve platform reliability",
    actor: "Taylor Reed",
    role: "manager",
    timestamp: "2026-01-15T10:05:00Z",
    details: "Approved goal aligned with platform OKRs.",
  },
  {
    id: "a3",
    type: "quarterly_update",
    goalId: "g4",
    goalTitle: "Reduce API latency",
    actor: "Morgan Chen",
    role: "employee",
    timestamp: "2026-01-22T16:40:00Z",
    details: "Progress updated to 71% after cache layer deployment.",
  },
  {
    id: "a4",
    type: "comment_added",
    goalId: "g6",
    goalTitle: "Increase enterprise pipeline",
    actor: "Jordan Lee",
    role: "manager",
    timestamp: "2026-02-10T14:30:00Z",
    details: "Manager comment: pipeline velocity behind plan.",
  },
  {
    id: "a5",
    type: "rejection",
    goalId: "g8",
    goalTitle: "Launch partner co-sell program",
    actor: "Jordan Lee",
    role: "manager",
    timestamp: "2026-02-12T11:20:00Z",
    details: "Rejected pending clearer partner KPIs.",
  },
  {
    id: "a6",
    type: "goal_created",
    goalId: "g10",
    goalTitle: "Improve campaign ROI",
    actor: "Sam Patel",
    role: "employee",
    timestamp: "2026-02-01T08:30:00Z",
    details: "Submitted Q2 marketing efficiency goal.",
  },
  {
    id: "a7",
    type: "approval",
    goalId: "g9",
    goalTitle: "Grow inbound MQL volume",
    actor: "Alex Rivera",
    role: "admin",
    timestamp: "2026-02-03T13:00:00Z",
    details: "Admin verified compliance before final approval.",
  },
  {
    id: "a8",
    type: "quarterly_update",
    goalId: "g12",
    goalTitle: "Reduce time-to-hire",
    actor: "Casey Wu",
    role: "employee",
    timestamp: "2026-02-14T10:15:00Z",
    details: "Progress updated to 35%; interview loop pilot started.",
  },
  {
    id: "a9",
    type: "unlock",
    goalId: "g2",
    goalTitle: "Accelerate feature delivery",
    actor: "Alex Rivera",
    role: "admin",
    timestamp: "2026-02-16T09:45:00Z",
    details: "Admin unlocked goal for mid-cycle description edit.",
  },
  {
    id: "a10",
    type: "approval",
    goalId: "g14",
    goalTitle: "Hit regional revenue target",
    actor: "Alex Rivera",
    role: "admin",
    timestamp: "2026-02-17T15:30:00Z",
    details: "Regional revenue goal approved for Q1 tracking.",
  },
];

export function cloneDemoGoals(): Goal[] {
  return structuredClone(DEMO_GOALS);
}

export function cloneDemoAudit(): AuditEvent[] {
  return structuredClone(DEMO_AUDIT);
}

export const DEFAULT_DEMO_USER = DEMO_USERS[0];
